[package]
name = "crambly"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.102", features = ["backtrace"] }
camino = "1.2.2"
pratt = { git = "https://github.com/Alex-Shand/pratt.git" }

[dev-dependencies]
pretty_assertions = "1.4.1"
